<?php
/**
 * @file
 * Install file for PhotoLDR module.
 */

/**
 * Implements hook_install().
 */
function photoldr_install() {
  // No install tasks.
}


/**
 * Implements hook_uninstall().
 *
 * Remove all the variables that might have been set while
 * this module was enabled.
 */
function photoldr_uninstall() {
  db_delete('variable')
    ->condition('name', "photoldr%", "LIKE")
    ->execute();

  cache_clear_all('variables', 'cache_bootstrap');
}
