<?php
// $Id$
/**
 * @file
 * Install file for PhotoLDR module.
 *
 */

/**
 * Implements hook_install().
 */
 
function photoldr_install() {
  
  
}

/**
 * Implements hook_uninstall().
 */
function photoldr_uninstall() {
  // Remove all the variables that might have been set while this
  // module was enabled.  

  db_delete('variable')
    ->condition('name', "photoldr%", "LIKE")
    ->execute();

  cache_clear_all('variables', 'cache_bootstrap');
}

