<?php
// $Id$
/**
 * @file
 * Module for guiding new users.
 */
 

/**
 * Implements hook_block_info().
 *
 * For another example of using block hook functions, see:
 * http://api.drupal.org/api/examples/block_example--block_example.module/7
 *
 * Learn more about hook_block_info() at:
 * http://api.drupal.org/api/drupal/modules--block--block.api.php/function/hook_block_info/7
 *
 */
function photoldr_block_block_info() {
  $blocks['photoldr_block'] = array(
    'info' => t('PhotoLDR Block'),
  );
  $blocks['photoldr_block_ios'] = array(
    'info' => t('PhotoLDR Block for iOS Devices'),
  );
  return $blocks;
}



/**
 * Implementation of hook_block_view
 */
function photoldr_block_block_view($delta=0) {
  global $user;
  global $base_url;
  $hostname = variable_get('Photoldr_FQDN', $base_url['host']);
  $block = array();
  $block['subject'] = '';
  $block['content'] = l(t('Use PhotoLDR App'), 'photoldr://' . $hostname);
  $build = array();


  $block['subject'] = t('PhotoLDR App');
  $build = array(
    'header_text' => array(
      '#type' => 'markup',
      '#markup' => '<article>'
            . t('Step') . '1: ' . l(t('Create your account'), 'user/register') . '</br>'
            . t('Step') . '2: ' . l(t('Install the App'), 'http://itunes.apple.com/us/app/photoldr/id555194288?ls=1&mt=8') . '</br>'
            . t('Step') . '3: <a href="photoldr://' . $hostname. '">' . t('Start Using the App') . '</a></br>'
            . '</article>'
      ,
    ),
  );
  $block_content = drupal_render($build);
  $block['content'] = $block_content;


  return $block;
}



/**
 * Implementation of hook_block_view
 *
 * Only display on iOS devices
 */
function photoldr_block_ios_block_view($delta=0) {
  
  if (!(preg_match('/(iphone|ipad|ipod)/i', strtolower($_SERVER['HTTP_USER_AGENT'])))) {
    //TODO uncomment the return so that only iOS devices see the link
    return;
  }

  return photoldr_block_block_view();
}